changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security and governance
      labels:
        - security
        - dependencies
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - '*'
